### ISSUE TITLE
Planned Release?

### ISSUE THREAD

**Issue by dpetzel** [RoboticCheese/clamav-chef#40]
Any chance your planning a release in the near future? I noticed today I was bumping up against the issue resolved in this commit https://github.com/RoboticCheese/clamav-chef/commit/145d4cf7851e00514e73ca175c1c9bc0ff7a36db, however that doesn't appear to be included in the latest released version. I can certainly work around this in my wrapper cookbook,but if you've got a release coming, I'd rather just use that.

Thanks (PS nice job on this cookbook, saving me a bunch of time).

**Comment by veurits** [comment]
yes please release 1.0.3

**Comment by RoboticCheese** [comment]
There was a bunch of stuff that needed updating to get the build passing again. That's been done and the latest source released as 1.1.0.
