### ISSUE TITLE
Add CentOS 7 support

### ISSUE THREAD

**Issue by RoboticCheese** [RoboticCheese/clamav-chef#42]
CentOS 7 has a different set of package names. Among other things, it has separate server packages for sysvinit and systemd.

**Comment by av1nashs1ngh** [comment]
Hi, we ran into this issue a while ago and fixed it for our environment. We thought it would be nice to give it back to the community. Can you please have a look and merge this? Thanks! :+1:

**Comment by kciredor** [comment]
+1
