### ISSUE TITLE
ubuntu ppa is not found 404

### ISSUE THREAD

**Issue by brenguy** [RoboticCheese/clamav-chef#60]
The clamav ubuntu PPA repository no longer exists and will need to be updated. 
https://launchpad.net/~ubuntu-clamav

My ubuntu 14.04 was still able to install clamav as I believe this is in the stock repos.

**Comment by RoboticCheese** [comment]
This was fixed by #57 and released in v1.3.0. The cookbook no longer adds that repo.

**Comment by brenguy** [comment]
Sorry! Had the prior version and did not notice Thanks!!
